/* ============================================================================
   QUERIES SQL PARA FIREBIRD

   Copia y pega estas queries en isql o FlameRobin
   ============================================================================ */

-- ============ 1. PRODUCTOS ============

-- Listar todos los productos con categoría
SELECT
  P.ID,
  P.NOMBRE,
  P.DESCRIPCION,
  P.PRECIO,
  P.STOCK,
  C.NOMBRE as CATEGORIA
FROM PRODUCTOS P
JOIN CATEGORIAS C ON P.CATEGORIA_ID = C.ID
ORDER BY C.NOMBRE, P.NOMBRE;

-- Productos por categoría
SELECT
  P.ID,
  P.NOMBRE,
  P.PRECIO,
  P.STOCK
FROM PRODUCTOS P
JOIN CATEGORIAS C ON P.CATEGORIA_ID = C.ID
WHERE C.NOMBRE = 'Tecnología'
ORDER BY P.NOMBRE;

-- Productos con bajo stock
SELECT
  NOMBRE,
  STOCK,
  PRECIO,
  STOCK * PRECIO as VALOR_INVENTARIO
FROM PRODUCTOS
WHERE STOCK < 10
ORDER BY STOCK ASC;

-- Valor total por categoría
SELECT
  C.NOMBRE as CATEGORIA,
  COUNT(P.ID) as TOTAL_PRODUCTOS,
  SUM(P.STOCK) as TOTAL_STOCK,
  SUM(P.STOCK * P.PRECIO) as VALOR_TOTAL
FROM PRODUCTOS P
JOIN CATEGORIAS C ON P.CATEGORIA_ID = C.ID
GROUP BY C.ID, C.NOMBRE
ORDER BY VALOR_TOTAL DESC;

-- ============ 2. CARRITO ============

-- Ver carrito de un usuario
SELECT
  C.ID,
  P.NOMBRE,
  P.PRECIO,
  C.CANTIDAD,
  (P.PRECIO * C.CANTIDAD) as SUBTOTAL
FROM CARRITO C
JOIN PRODUCTOS P ON C.PRODUCTO_ID = P.ID
WHERE C.USUARIO_ID = 'user-001'
ORDER BY C.CREATED_AT DESC;

-- Total del carrito por usuario
SELECT
  C.USUARIO_ID,
  COUNT(DISTINCT C.PRODUCTO_ID) as CANTIDAD_PRODUCTOS,
  SUM(C.CANTIDAD) as TOTAL_ITEMS,
  SUM(P.PRECIO * C.CANTIDAD) as TOTAL
FROM CARRITO C
JOIN PRODUCTOS P ON C.PRODUCTO_ID = P.ID
GROUP BY C.USUARIO_ID;

-- ============ 3. PEDIDOS ============

-- Ver todos los pedidos
SELECT
  P.ID,
  P.USUARIO_ID,
  EP.NOMBRE as ESTADO,
  P.TOTAL,
  P.CREATED_AT,
  P.UPDATED_AT
FROM PEDIDOS P
JOIN ESTADO_PEDIDO EP ON P.ESTADO_ID = EP.ID
ORDER BY P.CREATED_AT DESC;

-- Pedidos de un usuario
SELECT
  P.ID,
  EP.NOMBRE as ESTADO,
  P.TOTAL,
  COUNT(DP.ID) as CANTIDAD_PRODUCTOS,
  P.CREATED_AT
FROM PEDIDOS P
JOIN ESTADO_PEDIDO EP ON P.ESTADO_ID = EP.ID
LEFT JOIN DETALLES_PEDIDO DP ON P.ID = DP.PEDIDO_ID
WHERE P.USUARIO_ID = 'user-001'
GROUP BY P.ID, EP.NOMBRE, P.TOTAL, P.CREATED_AT
ORDER BY P.CREATED_AT DESC;

-- Detalles de un pedido específico
SELECT
  DP.NOMBRE_PRODUCTO,
  DP.CANTIDAD,
  DP.PRECIO_UNITARIO,
  DP.SUBTOTAL,
  P.TOTAL as TOTAL_PEDIDO,
  EP.NOMBRE as ESTADO
FROM DETALLES_PEDIDO DP
JOIN PEDIDOS P ON DP.PEDIDO_ID = P.ID
JOIN ESTADO_PEDIDO EP ON P.ESTADO_ID = EP.ID
WHERE P.ID = 'pedido-id-aqui'
ORDER BY DP.CREATED_AT;

-- Pedidos por estado
SELECT
  EP.NOMBRE as ESTADO,
  COUNT(P.ID) as CANTIDAD_PEDIDOS,
  SUM(P.TOTAL) as VALOR_TOTAL,
  AVG(P.TOTAL) as VALOR_PROMEDIO
FROM PEDIDOS P
JOIN ESTADO_PEDIDO EP ON P.ESTADO_ID = EP.ID
GROUP BY EP.ID, EP.NOMBRE
ORDER BY CANTIDAD_PEDIDOS DESC;

-- ============ 4. DETALLES PEDIDO ============

-- Productos más vendidos
SELECT
  DP.NOMBRE_PRODUCTO,
  SUM(DP.CANTIDAD) as TOTAL_VENDIDO,
  SUM(DP.SUBTOTAL) as INGRESOS,
  COUNT(DISTINCT DP.PEDIDO_ID) as NUM_PEDIDOS
FROM DETALLES_PEDIDO DP
JOIN PEDIDOS P ON DP.PEDIDO_ID = P.ID
WHERE P.ESTADO_ID IN (2, 3, 4)
GROUP BY DP.NOMBRE_PRODUCTO
ORDER BY TOTAL_VENDIDO DESC;

-- Valor promedio por usuario
SELECT
  P.USUARIO_ID,
  COUNT(P.ID) as NUM_COMPRAS,
  AVG(P.TOTAL) as TICKET_PROMEDIO,
  SUM(P.TOTAL) as TOTAL_GASTADO
FROM PEDIDOS P
WHERE P.ESTADO_ID IN (2, 3, 4)
GROUP BY P.USUARIO_ID
ORDER BY TOTAL_GASTADO DESC;

-- ============ 5. ACTUALIZAR ESTADO ============

-- Cambiar estado de un pedido
UPDATE PEDIDOS
SET ESTADO_ID = 2,
    UPDATED_AT = CURRENT_TIMESTAMP
WHERE ID = 'pedido-id-aqui';

-- Marcar como Enviado todos los pagados hace 1 día
UPDATE PEDIDOS
SET ESTADO_ID = 3,
    UPDATED_AT = CURRENT_TIMESTAMP
WHERE ESTADO_ID = 2
AND CREATED_AT < CURRENT_TIMESTAMP - INTERVAL '1' DAY;

-- ============ 6. INSERTAR DATOS ============

-- Insertar usuario
INSERT INTO USUARIOS (ID, EMAIL, PASSWORD_HASH, NOMBRE)
VALUES ('user-002', 'nuevo@example.com', 'password123', 'Nuevo Usuario');

-- Agregar producto al carrito
INSERT INTO CARRITO (ID, USUARIO_ID, PRODUCTO_ID, CANTIDAD)
VALUES ('cart-001', 'user-001', 'prod-001', 2);

-- Crear pedido
INSERT INTO PEDIDOS (ID, USUARIO_ID, ESTADO_ID, TOTAL)
VALUES ('pedido-001', 'user-001', 1, 1250.00);

-- Agregar detalle al pedido
INSERT INTO DETALLES_PEDIDO (ID, PEDIDO_ID, PRODUCTO_ID, NOMBRE_PRODUCTO, CANTIDAD, PRECIO_UNITARIO, SUBTOTAL)
VALUES ('detail-001', 'pedido-001', 'prod-001', 'Laptop ASUS', 1, 599.99, 599.99);

-- ============ 7. LIMPIAR DATOS ============

-- Ver carritos abandonados hace más de 7 días
SELECT
  C.USUARIO_ID,
  COUNT(C.ID) as ITEMS,
  SUM(P.PRECIO * C.CANTIDAD) as VALOR,
  C.UPDATED_AT
FROM CARRITO C
JOIN PRODUCTOS P ON C.PRODUCTO_ID = P.ID
WHERE C.UPDATED_AT < CURRENT_TIMESTAMP - INTERVAL '7' DAY
GROUP BY C.USUARIO_ID, C.UPDATED_AT
ORDER BY C.UPDATED_AT DESC;

-- Eliminar carrito abandonado
DELETE FROM CARRITO
WHERE USUARIO_ID = 'user-001'
AND UPDATED_AT < CURRENT_TIMESTAMP - INTERVAL '30' DAY;

-- ============ 8. VERIFICAR TABLAS ============

-- Contar filas en cada tabla
SELECT 'CATEGORIAS' as TABLA, COUNT(*) as TOTAL FROM CATEGORIAS
UNION ALL
SELECT 'PRODUCTOS', COUNT(*) FROM PRODUCTOS
UNION ALL
SELECT 'PRODUCTOS', COUNT(*) FROM PRODUCTOS
UNION ALL
SELECT 'USUARIOS', COUNT(*) FROM USUARIOS
UNION ALL
SELECT 'CARRITO', COUNT(*) FROM CARRITO
UNION ALL
SELECT 'PEDIDOS', COUNT(*) FROM PEDIDOS
UNION ALL
SELECT 'DETALLES_PEDIDO', COUNT(*) FROM DETALLES_PEDIDO;
